module.exports = {
    SHOPIFY_SHOPNAME: process.env.SHOPIFY_SHOPNAME,
    SHOPIFY_APIKEY: process.env.SHOPIFY_APIKEY,
    SHOPIFY_PASSWORD: process.env.SHOPIFY_PASSWORD,
    SHOPIFY_DBURL: process.env.SHOPIFY_DBURL,
    SHOPIFY_DBNAME: process.env.SHOPIFY_DBNAME,
    SHOPIFY_COLLECTIONNAME: process.env.SHOPIFY_COLLECTIONNAME,
    SHOPIFY_SQSURL: process.env.SHOPIFY_SQSURL,
    STORE_COLLECTIONNAME: process.env.STORE_COLLECTIONNAME,
}